eureka:
  defaultZone: http://127.0.0.1:8000/eureka/

app:
  datasource:
    name: demo_admin
    host: 10.0.0.42:3306
    username: root
    password: vpclub.wuhan
  redis:
    host: 127.0.0.1
    port: 6379
    password:
