
eureka:
  defaultZone: http://10.0.0.46:8000/eureka/

app:
  datasource:
    name: demo_admin
    host: 10.0.0.42:3306
    username: root
    password: 123456
  redis:
    host: 10.0.0.46
    port: 6379
    password: vpclub123

logging:
  level:
    com.netflix: info